# Generated by Django 4.1.3 on 2022-12-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["rcs_id", "first_name", "last_name"]},
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="credits",
            field=models.IntegerField(
                default=0,
                help_text="How many course credits the user is participating in RCOS for this semester. 0 means just for experience.",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_for_pay",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user is participating in RCOS for pay instead of course credit",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description_markdown",
            field=models.TextField(
                help_text="A long description of the project. Supports Markdown.",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the project has been approved by Mentors/Coordinators to participate in RCOS",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_seeking_members",
            field=models.BooleanField(
                default=False,
                help_text="Whether the project is actively looking for new members to join",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                help_text="The project's unique name", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                help_text="The user that can make edits to the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projects",
                to="portal.user",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tagline",
            field=models.CharField(
                help_text="A one-line description of the project", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="end_date",
            field=models.DateField(
                help_text="The last day of the semester according to the RPI Academic Calendar: https://info.rpi.edu/registrar/academic-calendar",
                verbose_name="end of semester",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="id",
            field=models.CharField(
                help_text="The unique ID of the semseter in RPI's format of YYYYMM where YYYY is the starting year and MM is the starting month.",
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="start_date",
            field=models.DateField(
                help_text="The first day of the semester according to the RPI Academic Calendar: https://info.rpi.edu/registrar/academic-calendar",
                verbose_name="start of semester",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_user_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The user's Discord account ID from the Discord API",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The user's primary email, used for logging in and sending communications. Can change.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="github_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The user's GitHub username (not user ID)",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="graduation_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If the user is an RPI user, their graduation year.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="rcs_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If the user is an RPI user, their RCS ID.",
                max_length=30,
                verbose_name="RCS ID",
            ),
            preserve_default=False,
        ),
    ]
