# Generated by Django 4.1.4 on 2022-12-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("rpi", "RPI"), ("external", "External")],
                default="external",
                max_length=30,
            ),
        ),
    ]
