# Generated by Django 4.1.4 on 2023-01-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_user_id",
            field=models.CharField(
                blank=True,
                help_text="The user's Discord account ID from the Discord API",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_username",
            field=models.CharField(
                blank=True,
                help_text="The user's GitHub username (not user ID)",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
