# Generated by Django 4.1.3 on 2022-12-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semester",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name", "username", "email"]},
        ),
        migrations.RenameField(
            model_name="projectrepository",
            old_name="repository_url",
            new_name="url",
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="portal.projecttag"
            ),
        ),
    ]
