# Generated by Django 4.1.4 on 2022-12-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
