# Generated by Django 4.1.4 on 2023-01-18 16:55

from django.db import migrations

import portal.models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_alter_user_managers_alter_user_rcs_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", portal.models.UserManager()),
            ],
        ),
    ]
