# Generated by Django 4.1.4 on 2023-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_projectpitch_url_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["name", "summary"], name="portal_proj_name_c901dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_approved"], name="portal_user_is_appr_2439f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="portal_user_email_8d6b8e_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["rcs_id"], name="portal_user_rcs_id_47e388_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="portal_user_first_n_13e075_idx",
            ),
        ),
    ]
