# Generated by Django 4.1.3 on 2022-12-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_meeting_meetingattendance_meeting_attendances_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["starts_at"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="enrollments",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="is_coordinator",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="portal.project",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the meeting is visible to users",
                verbose_name="published?",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="end_date",
            field=models.DateField(
                help_text="The last day of the semester according to the RPI Academic Calendar: https://info.rpi.edu/registrar/academic-calendar",
                verbose_name="last semester",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="is_accepting_new_projects",
            field=models.BooleanField(
                default=False,
                help_text="Whether new projects can be proposed for this semester",
                verbose_name="accepting new projects?",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="start_date",
            field=models.DateField(
                help_text="The first day of the semester according to the RPI Academic Calendar: https://info.rpi.edu/registrar/academic-calendar",
                verbose_name="first day",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="approved?"),
        ),
    ]
