# Generated by Django 4.1.3 on 2022-12-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_semester_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description_markdown",
        ),
        migrations.AlterField(
            model_name="project",
            name="summary",
            field=models.CharField(
                help_text="A one-line summary of the project", max_length=100
            ),
        ),
    ]
