# Generated by Django 4.1.4 on 2023-01-20 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_remove_project_portal_proj_name_ae220a_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "email_domain",
                    models.CharField(
                        help_text="The email domain used to auto-associate users to this org.",
                        max_length=100,
                    ),
                ),
                (
                    "email_domain_secondary",
                    models.CharField(
                        blank=True,
                        help_text="A secondary email domain used to auto-associate users to this org.",
                        max_length=100,
                    ),
                ),
                (
                    "homepage_url",
                    models.URLField(
                        help_text="The public homepage of the organization."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization this user belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="portal.organization",
            ),
        ),
    ]
