# Generated by Django 4.1.4 on 2023-01-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_seeking_members",
        ),
    ]
