# Generated by Django 4.1.3 on 2022-12-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_meeting_options_remove_project_enrollments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="is_coordinator",
            field=models.BooleanField(default=False, verbose_name="coordinator?"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_faculty_advisor",
            field=models.BooleanField(default=False, verbose_name="faculty advisor?"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_for_pay",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user is participating in RCOS for pay instead of course credit",
                verbose_name="for pay?",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="is_project_lead",
            field=models.BooleanField(default=False, verbose_name="project lead?"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="portal.semester",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="end_date",
            field=models.DateField(
                help_text="The last day of the semester according to the RPI Academic Calendar: https://info.rpi.edu/registrar/academic-calendar",
                verbose_name="last day",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("semester", "user")},
        ),
    ]
