# Generated by Django 4.1.3 on 2022-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_remove_project_description_markdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="notes_markdown",
            field=models.TextField(
                blank=True,
                help_text="Private notes for admins about this user for this semester",
                max_length=10000,
            ),
        ),
    ]
