# Generated by Django 4.1.4 on 2023-01-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_project_homepage_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingattendance",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="MeetingAttendanceCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.meeting"
                    ),
                ),
                (
                    "small_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.smallgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
