# Generated by Django 4.1.3 on 2022-12-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_enrollment_notes_markdown"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectpresentation",
            old_name="presentation_url",
            new_name="url",
        ),
        migrations.RenameField(
            model_name="projectproposal",
            old_name="proposal_url",
            new_name="url",
        ),
        migrations.CreateModel(
            name="ProjectPitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(help_text="Link to the pitch presentation")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="portal.project",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_pitches",
                        to="portal.semester",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
