# Generated by Django 4.1.4 on 2023-01-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_meetingattendance_is_verified_meetingattendancecode"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meetingattendance",
            unique_together={("meeting", "user")},
        ),
    ]
