# Generated by Django 4.1.3 on 2022-12-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_alter_enrollment_is_coordinator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmallGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Public-facing name of the Small Group",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="The location the Small Group meets for Small Group meetings",
                        max_length=200,
                    ),
                ),
                ("discord_category_id", models.CharField(blank=True, max_length=200)),
                ("discord_role_id", models.CharField(blank=True, max_length=200)),
                (
                    "mentors",
                    models.ManyToManyField(
                        related_name="mentored_small_groups", to="portal.user"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small_groups",
                        to="portal.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["semester", "name", "location"],
            },
        ),
    ]
