# Generated by Django 4.1.3 on 2022-12-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_smallgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="smallgroup",
            name="projects",
            field=models.ManyToManyField(
                related_name="small_groups", to="portal.project"
            ),
        ),
    ]
