# Generated by Django 4.1.3 on 2022-12-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_rename_presentation_url_projectpresentation_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpresentation",
            name="grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="The grade assigned to this presentation",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectproposal",
            name="grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="The grade assigned to this proposal",
                max_digits=3,
                null=True,
            ),
        ),
    ]
