# Generated by Django 4.1.4 on 2023-01-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_project_organization_alter_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="discord_role_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email_domain",
            field=models.CharField(
                blank=True,
                help_text="The email domain used to auto-associate users to this org.",
                max_length=100,
            ),
        ),
    ]
