# Generated by Django 4.1.4 on 2023-01-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_alter_meetingattendance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meetingattendancecode",
            unique_together={("code", "meeting", "small_group")},
        ),
    ]
