# Generated by Django 4.1.3 on 2022-12-06 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_smallgroup_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional title to display on Status Update page",
                        max_length=200,
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        help_text="The date and time the status update opens for submissions"
                    ),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        help_text="The date and time the status update stops accepting submissions"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="portal.semester",
                    ),
                ),
            ],
            options={
                "ordering": ("semester", "opens_at"),
                "get_latest_by": "opens_at",
            },
        ),
    ]
