# Generated by Django 4.1.4 on 2023-01-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_alter_meetingattendancecode_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingattendancecode",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_codes",
                to="portal.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="meetingattendancecode",
            name="small_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_codes",
                to="portal.smallgroup",
            ),
        ),
    ]
