# Generated by Django 4.1.4 on 2023-01-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_organization_discord_role_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterField(
            model_name="projecttag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
