# Generated by Django 4.1.3 on 2022-12-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_statusupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusUpdateSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="The grade assigned to this submission",
                        max_digits=1,
                    ),
                ),
                (
                    "grader_comments",
                    models.TextField(
                        blank=True,
                        help_text="Optional comments from the grader to the submitter",
                        max_length=10000,
                    ),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_status_update_submissions",
                        to="portal.user",
                    ),
                ),
                (
                    "status_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="portal.statusupdate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_update_submissions",
                        to="portal.user",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
