# Generated by Django 4.1.4 on 2023-01-24 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_alter_user_options_alter_projecttag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="is_accepting_mentors",
            field=models.BooleanField(
                default=False,
                help_text="Whether users can apply to be Mentors for this semester",
                verbose_name="accepting mentor applications?",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="external_chat_url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL to an external chat that this project uses (e.g. a Discord invite link)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The external organization this project belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="portal.organization",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                help_text="The user that can edit the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="name",
            field=models.CharField(
                help_text="User-facing name of semester, e.g. Fall 2024", max_length=30
            ),
        ),
        migrations.CreateModel(
            name="MentorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "why",
                    models.TextField(
                        help_text="Why do you want to be a Mentor?", max_length=10000
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=None,
                        help_text="Was this application accepted",
                        null=True,
                        verbose_name="approved?",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_applications",
                        to="portal.semester",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="What skills can you offer help for?",
                        related_name="mentors",
                        to="portal.projecttag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
