# Generated by Django 4.1.3 on 2022-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_statusupdatesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdatesubmission",
            name="blockers",
            field=models.TextField(default="", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statusupdatesubmission",
            name="next_week",
            field=models.TextField(default="", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statusupdatesubmission",
            name="previous_week",
            field=models.TextField(default="", max_length=10000),
            preserve_default=False,
        ),
    ]
