# Generated by Django 4.1.4 on 2023-01-24 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_semester_is_accepting_mentors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mentorapplication",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="mentorapplication",
            name="is_accepted",
            field=models.BooleanField(
                default=None,
                help_text="Was this application accepted",
                null=True,
                verbose_name="accepted?",
            ),
        ),
        migrations.CreateModel(
            name="ProjectEnrollmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_accepted", models.BooleanField(default=None, null=True)),
                (
                    "why",
                    models.TextField(
                        help_text="Why you want to join the project?", max_length=10000
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        help_text="What prior knowledge/experience related to this project do you have?",
                        max_length=10000,
                    ),
                ),
                (
                    "approval_reasoning",
                    models.CharField(
                        blank=True,
                        help_text="Why the project lead accepted/rejected the application",
                        max_length=200,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_applications",
                        to="portal.project",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_enrollment_applications",
                        to="portal.semester",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_enrollment_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
