# Generated by Django 4.1.3 on 2022-12-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_statusupdatesubmission_blockers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusupdatesubmission",
            name="grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="The grade assigned to this submission",
                max_digits=1,
            ),
        ),
        migrations.AlterField(
            model_name="statusupdatesubmission",
            name="grader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_status_update_submissions",
                to="portal.user",
            ),
        ),
    ]
