# Generated by Django 4.1.4 on 2023-01-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0010_remove_mentorapplication_is_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectenrollmentapplication",
            name="approval_reasoning",
        ),
        migrations.AddField(
            model_name="projectenrollmentapplication",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                help_text="Why the project lead rejected the application",
                max_length=200,
            ),
        ),
    ]
