# Generated by Django 4.1.4 on 2023-01-24 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0011_remove_projectenrollmentapplication_approval_reasoning_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorapplication",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_applications",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
