# Generated by Django 4.1.4 on 2023-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0012_mentorapplication_user"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["start_date", "end_date"], name="portal_seme_start_d_7649b7_idx"
            ),
        ),
    ]
