# Generated by Django 4.1.4 on 2023-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_semester_portal_seme_start_d_7649b7_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["start_date"], name="portal_seme_start_d_c8b5dc_idx"
            ),
        ),
    ]
