# Generated by Django 4.1.4 on 2023-01-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0014_semester_portal_seme_start_d_c8b5dc_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="is_accepting_mentors",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="is_accepting_new_projects",
        ),
        migrations.AddField(
            model_name="semester",
            name="enrollment_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="The last date users can enroll in the semester (not with a project yet)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="mentor_application_deadline",
            field=models.BooleanField(
                blank=True,
                help_text="The last date students can apply to be Mentors for this semester",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="project_enrollment_application_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="The last date users can apply to a project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="project_pitch_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="semester",
            name="project_proposal_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="projectpresentation",
            unique_together={("semester", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="projectproposal",
            unique_together={("semester", "project")},
        ),
    ]
