# Generated by Django 4.1.4 on 2023-01-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0017_remove_semester_mentor_application_deadline_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="semester",
            old_name="mentor_application_deadlines",
            new_name="mentor_application_deadline",
        ),
    ]
