# Generated by Django 4.1.4 on 2023-01-26 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0019_alter_enrollment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="graduation_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If the user is an RPI user, their graduation year.",
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(2028),
                    django.core.validators.MinValueValidator(1950),
                ],
            ),
        ),
    ]
