# Generated by Django 4.1.4 on 2023-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0021_meetingattendancecode_portal_meet_code_a7947d_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["user", "semester"], name="portal_enro_user_id_794ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["user"], name="portal_enro_user_id_c0e760_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["semester"], name="portal_enro_semeste_4fab39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["semester", "project"], name="portal_enro_semeste_508d3f_idx"
            ),
        ),
    ]
