# Generated by Django 4.1.4 on 2023-01-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0023_alter_enrollment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="Optional URL to a logo for the project"
            ),
        ),
    ]
