# Generated by Django 4.1.4 on 2023-01-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0025_meeting_attendance_chance_verification_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="recording_url",
            field=models.URLField(
                blank=True, help_text="The URL to the meeting's recording (optional)"
            ),
        ),
    ]
