# Generated by Django 4.1.4 on 2023-02-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0026_meeting_recording_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_attendance_taken",
            field=models.BooleanField(
                default=True,
                help_text="Whether attendance is taken at this meeting. If false, all expected users are counted as attended.",
                verbose_name="attendance taken?",
            ),
        ),
    ]
