# Generated by Django 4.1.4 on 2023-02-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0027_alter_project_description_alter_project_owner"),
        ("portal", "0027_meeting_is_attendance_taken"),
    ]

    operations = []
