# Generated by Django 4.1.4 on 2023-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0028_merge_20230205_2042"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="meetingattendancecode",
            name="unique_meeting_attendance_small_group_code",
        ),
        migrations.AddConstraint(
            model_name="meetingattendancecode",
            constraint=models.UniqueConstraint(
                fields=("meeting", "small_group"),
                name="unique_meeting_attendance_small_group_code",
            ),
        ),
    ]
