# Generated by Django 4.1.4 on 2023-02-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0030_alter_meetingattendancecode_small_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingattendancecode",
            name="small_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_codes",
                to="portal.smallgroup",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingattendancecode",
            index=models.Index(
                fields=["meeting"], name="portal_meet_meeting_10702e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingattendancecode",
            index=models.Index(
                fields=["meeting", "small_group"], name="portal_meet_meeting_04b0e3_idx"
            ),
        ),
    ]
