# Generated by Django 4.2 on 2023-05-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0031_alter_meetingattendancecode_small_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("building", models.CharField(max_length=100)),
                ("room", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="semester",
            name="project_pitch_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="The last date users can pitch a project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="portal.room",
            ),
        ),
        migrations.AddField(
            model_name="smallgroup",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="portal.room",
            ),
        ),
    ]
