# Generated by Django 4.2.1 on 2023-05-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0033_semester_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smallgroup",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="The location the Small Group meets for Small Group meetings",
                max_length=200,
            ),
        ),
    ]
