# Generated by Django 4.2.1 on 2023-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0034_alter_smallgroup_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="semesters", to="portal.room"
            ),
        ),
    ]
