# Generated by Django 4.2.1 on 2023-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0035_alter_semester_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="type",
            field=models.CharField(
                choices=[
                    ("small_group", "Small Group"),
                    ("large_group", "Large Group"),
                    ("workshop", "Workshop"),
                    ("mentor", "Mentor"),
                    ("coordinator", "Coordinator"),
                ],
                default="small_group",
                max_length=100,
            ),
        ),
    ]
