# Generated by Django 4.2.1 on 2023-05-22 20:56

import django.db.models.deletion
from django.db import migrations, models

import portal.models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0036_alter_meeting_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="semester",
            field=models.ForeignKey(
                default=portal.models.Semester.get_active,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="portal.semester",
            ),
        ),
    ]
