# Generated by Django 4.2.1 on 2023-05-27 01:48

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_alter_meeting_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smallgroup',
            options={'ordering': ['semester', django.db.models.functions.text.Lower('name'), 'room']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='smallgroup',
            name='location',
        ),
    ]
