# Generated by Django 4.2.1 on 2023-06-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0039_alter_meeting_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorapplication",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="What skills can you offer help for?",
                related_name="mentor_applications",
                to="portal.projecttag",
            ),
        ),
    ]
