# Generated by Django 4.2.2 on 2023-10-15 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_alter_meeting_room_alter_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendance',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The user that submitted the attendance for user (either them or an administrator).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Use Ctrl or Cmd to select multiple tags that apply to your project.', related_name='projects', to='portal.projecttag'),
        ),
    ]
