# Generated by Django 4.2.5 on 2023-09-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_alter_project_tags_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='sub_title',
            new_name='description',
        ),
    ]
