# Generated by Django 4.2.2 on 2023-10-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_meetingattendance_submitted_by_alter_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingattendance',
            name='is_added_by_admin',
        ),
    ]
