# Generated by Django 4.2.5 on 2023-09-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_rename_sub_title_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
