# Generated by Django 5.0.2 on 2024-02-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_user_is_name_public'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['meeting'], name='portal_meet_meeting_88d7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['user'], name='portal_meet_user_id_40102c_idx'),
        ),
    ]
