# Generated by Django 4.2.5 on 2023-09-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
