# Generated by Django 4.2.5 on 2023-09-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Use Ctrl or Cmd to select multiple tags that apply to your blog post.', related_name='blog_posts', to='portal.projecttag'),
        ),
    ]
