# Generated by Django 5.2.5 on 2026-03-06 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0050_add_search_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="host",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional host for the meeting (e.g. mentor hosting a workshop)",
                limit_choices_to=models.Q(("role", "rpi")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["semester", "is_mentor"], name="portal_enro_semeste_ed14b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["semester", "is_coordinator"],
                name="portal_enro_semeste_08e97d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["semester", "is_project_lead"],
                name="portal_enro_semeste_54fec6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["project", "semester"], name="portal_enro_project_e76854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingattendance",
            index=models.Index(
                fields=["meeting", "is_verified"], name="portal_meet_meeting_b894a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingattendance",
            index=models.Index(
                fields=["meeting", "user"], name="portal_meet_meeting_5bb22b_idx"
            ),
        ),
    ]
