# Generated by Django 5.2.14 on 2026-06-01 15:16

import re

from django.db import migrations, models
from django.template.defaultfilters import slugify


def dedupe_project_slugs(apps, schema_editor):
    """Re-slug projects that share a slug so the unique constraint can be applied.

    `slugify` is lossy (e.g. "C++" and "C#" both become "c"), so distinct
    project names can collide on slug. The oldest project in each colliding
    group keeps its slug; the rest get a `-2`, `-3`, ... suffix. Generated
    slugs avoid every existing slug so no project "steals" another's URL.
    """
    Project = apps.get_model("portal", "Project")
    max_length = Project._meta.get_field("slug").max_length

    taken = set(Project.objects.values_list("slug", flat=True))
    seen: set[str] = set()

    # Oldest first so established projects keep their existing slug/URL.
    for project in Project.objects.order_by("created_at", "pk").iterator():
        slug = project.slug or slugify(project.name)[:max_length] or "project"

        if slug in seen:
            base = re.sub(r"-\d+$", "", slug)
            suffix = 2
            candidate = slug
            while candidate in seen or candidate in taken:
                tail = f"-{suffix}"
                candidate = f"{base[: max_length - len(tail)]}{tail}"
                suffix += 1
            slug = candidate

        if slug != project.slug:
            project.slug = slug
            project.save(update_fields=["slug"])

        seen.add(slug)
        taken.add(slug)


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0051_alter_meeting_host_and_more"),
    ]

    operations = [
        migrations.RunPython(dedupe_project_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
